/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Buttons: typeof import('./src/styles/components/Buttons')['Buttons']
  const CmCheckbox: typeof import('./src/styles/components/Selector')['CmCheckbox']
  const CmInput: typeof import('./src/styles/components/Textfield')['CmInput']
  const CmRadio: typeof import('./src/styles/components/Selector')['CmRadio']
  const Icon: typeof import('./src/components/Icon')['default']
  const autoPrefix: typeof import('./src/styles/helpers/mixins/Prefix')['autoPrefix']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const gapMargin: typeof import('./src/styles/helpers/mixins/Space')['gapMargin']
  const icon: typeof import('./src/styles/helpers/mixins/Icon')['icon']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const multiTruncate: typeof import('./src/styles/helpers/mixins/Typography')['multiTruncate']
  const space: typeof import('./src/styles/helpers/mixins/Space')['space']
  const startTransition: typeof import('react')['startTransition']
  const truncate: typeof import('./src/styles/helpers/mixins/Typography')['truncate']
  const typo: typeof import('./src/styles/helpers/mixins/Typography')['typo']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useHref: typeof import('react-router')['useHref']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInRouterContext: typeof import('react-router')['useInRouterContext']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useLocation: typeof import('react-router')['useLocation']
  const useMemo: typeof import('react')['useMemo']
  const useNavigate: typeof import('react-router')['useNavigate']
  const useNavigationType: typeof import('react-router')['useNavigationType']
  const useOutlet: typeof import('react-router')['useOutlet']
  const useOutletContext: typeof import('react-router')['useOutletContext']
  const useParams: typeof import('react-router')['useParams']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useResolvedPath: typeof import('react-router')['useResolvedPath']
  const useRoutes: typeof import('react-router')['useRoutes']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { IIcon } from './src/components/Icon'
  import('./src/components/Icon')
}
